###################################
#### This script receives a RNA expression matrix generated by hybridation/scanning and an annotation table.
####    The program retrieves separated differential expression tables for each the possible comparisons in a tsv format
####    As well as a list (RData) with the same information 
####    RNA program in https://github.com/raulmejia/DSP-Oszwald
####      
####     Input description:
####        expression matrix: tab separated, rows = featrures, cols= sources/samples, there should not be colname over the first column(for the rownames)
####        annotdf: rows = cols from the expression matrix, you should provide the name of column that contain your labels
####                Try to use character labels and if you have a "reference class" you can name it "Control" (case insensitive) the contrasts
####                against this category will be arranged properly and they will have priority
####     Output:
####        pdf, if your labels contain the word "Normal" (case insensitive) those graphs will be plotted first
####
####    Author of the script: Raúl Mejía
#### 
###################################
#### 0) loading and/or installing required libraries
###################################
if (!require("argparse")) {
  install.packages("argparse", ask =FALSE)
  library("argparse")
}
if (!require("gtools")) {
  install.packages("gtools", ask =FALSE)
  library("gtools")
}
if (!require("BiocManager")) {
  install.packages("BiocManager", ask =FALSE)
  library("BiocManager")
}
if (!require("limma")) {
  BiocManager::install("limma", ask =FALSE)
  library("limma")
}
if (!require("tidyverse")) {
  install.packages("tidyverse", ask =FALSE)
  library("tidyverse")
}
########################################
#### data given by the user
#########################################
myargs <- commandArgs(trailingOnly = TRUE)

# path_expression_matrix <- "/media/rmejia/mountme88/Projects/DSP/Data/Data_sent_by_DrAO_2020_12_11/Protein/Prunned/ExpMat_from_the_fitting_of--NucleiLog2_QnormBatchSep_combat_Prot_titleclean--n--protein_annotation_Raul_20201211_odd_deleted.tsv"
path_expression_matrix <- myargs[1]

# path_annotation_table <-"/media/rmejia/mountme88/Projects/DSP/Data/Data_sent_by_DrAO_2020_12_11/Protein/Prunned/Annot_table_from_the_fitting_of--NucleiLog2_QnormBatchSep_combat_Prot_titleclean--n--DSP_protein_annotation_Raul_20201211_odd_deleted_characters_instead_numbers.tsv"
path_annotation_table <- myargs[2]

# path_code <- "/media/rmejia/mountme88/code/DSP-Oszwald"
path_code <- myargs[3] 

# Folder_to_save_results <- "/media/rmejia/mountme88/Projects/DSP/Results/DEG/Protein/"
Folder_to_save_results <- myargs[4]

# column_of_labels_in_the_annotdf <- "label" # name of the column in your annotation data frame that contains the labels
column_of_labels_in_the_annotdf <- myargs[5]

# mylfc = 0
mylfc <- myargs[6]

# myp.value = 0.05
myp.value <- myargs[7]

# number_of_sets_4_the_VennDiagram <- 5
number_of_sets_4_the_VennDiagram <- myargs[8]

# Label_for_yor_results <- "Andre_GeoMx_Protein_DEG"
Label_for_yor_results <- myargs[9]


############################
###### Basic Processing of data given by the user for example Paths
############################
path_code <- normalizePath( path_code )
load_myMakeContrasts <- paste0(path_code,"/","libraries/makeallContrasts.R")
source(load_myMakeContrasts)

dir.create( Folder_to_save_results , recursive = TRUE)
Folder_to_save_results <- normalizePath(Folder_to_save_results)

############################
###### Body
#############################
# reading your matrices
myexpmat <- read.table( file= path_expression_matrix , sep="\t", header = TRUE, row.names = 1, check.names = FALSE)
annotdf <- read.table( file= path_annotation_table, sep="\t", header = TRUE, row.names = 1)

if( length(which( colnames(myexpmat)  %in% rownames(annotdf) )) != length(colnames(myexpmat))  ){
  print("The number columns in your expmat is different than the rows in your Annotation Table")
  quit()
}
if( length(which( colnames(myexpmat)  %in% rownames(annotdf) )) != length( rownames(annotdf) )  ){
  print("The number columns in your expmat is different than the rows in your Annotation Table")
  quit()
}
   
# Desgin Matrix
designmat <- model.matrix( ~0+  as.factor( annotdf [,column_of_labels_in_the_annotdf]) )
    colnames(designmat) <- levels(as.factor( annotdf [,column_of_labels_in_the_annotdf] ))
   
# Fitting the lineal model    
myfit <- lmFit( myexpmat, designmat  ) # fitting the linear model

mycontMat <- mymakeContrasts(designmat) # make your matrix of contrasts

myfit2 <- contrasts.fit( myfit, mycontMat)
myefit <- eBayes(myfit2) # moderate standard errors of the estimated log-fold changes

##################################################
### Creating the object to store the results
##################################################
list_TopTable_mylfc_n_pval <- list()
list_TopTable_mylfc_n_pval[[1]] <- topTable( myefit , coef=1, adjust="BH", p.value = myp.value, lfc = mylfc, number = Inf)
for(k in 2:dim(mycontMat)[2]){
  list_TopTable_mylfc_n_pval[[k]] <- topTable( myefit , coef=k, adjust="BH", p.value = myp.value, lfc = mylfc, number = Inf)
}
names(list_TopTable_mylfc_n_pval) <- colnames(mycontMat )

################################## 
## writing down the results
##################################
for( k in 1:length(list_TopTable_mylfc_n_pval) ){
  Name_of_theComparison <- str_replace_all( names(list_TopTable_mylfc_n_pval)[k], " ", "")
  path_file <- paste0(Folder_to_save_results,"/",Label_for_yor_results,"_Contrast...",Name_of_theComparison,".tsv")
    write.table( list_TopTable_mylfc_n_pval[[k]], file = path_file,  sep= "\t", quote=FALSE)
} # Saving all the DEG table with the cut parameters given by the user

path_RDS <-  paste0(Folder_to_save_results,"/",Label_for_yor_results,"_Contrast...all.rds")
saveRDS(list_TopTable_mylfc_n_pval, file=path_RDS)

##################################
###### Including a Venn Diagram
##################################
decidemyefit <-decideTests(myefit)

#Postions_of_colnames_containing_1 <- grep( "1", colnames(decidemyefit@.Data))
#Positions_no_containing_1 <- setdiff( 1:length(colnames(decidemyefit@.Data)) , Postions_of_colnames_containing_1 )
#col_order_priorizing_1 <- c( Postions_of_colnames_containing_1 , Positions_no_containing_1 )
#decidemyefit@.Data <- decidemyefit@.Data[ , col_order_priorizing_1 ]

#Postions_of_colnames_containing_Normal <- grep( "normal", colnames(decidemyefit@.Data), ignore.case = TRUE)
#Positions_no_containing_Normal <- setdiff( 1:length(colnames(decidemyefit@.Data)) , Postions_of_colnames_containing_Normal )
#col_order_priorizing_Normal <- c( Postions_of_colnames_containing_Normal , Positions_no_containing_Normal )
#decidemyefit@.Data <- decidemyefit@.Data[ , col_order_priorizing_Normal ]

decidemyefit_2_plot <- decidemyefit[ , 1:number_of_sets_4_the_VennDiagram]

path_2pdf <-  paste0(Folder_to_save_results,"/",Label_for_yor_results,"_VenDiagram.pdf")
pdf(file=path_2pdf )
vennDiagram(decidemyefit_2_plot)
vennDiagram(decidemyefit_2_plot, 
            include=c("up", "down"),
            counts.col=c("red", "blue"),
            circle.col = c("red", "blue", "green3"))
dev.off()

