###################################
#### This script recreives RNA expression matrix generated by hybridation/scanning and an annotation table.
####    The program retrieves separated differential expression tables for each the possible comparisons in a tsv format
####    As well as a list (RData) with the same information 
####    RNA program in https://github.com/raulmejia/DSP-Oszwald
####      
####     Input description:
####        expression matrix: tab separated, rows = featrures, cols= sources/samples
####        annotdf: rows = cols from the expression matrix, you should provide the name of column that contain your labels
####    Author of the script: Raúl Mejía
#### 
###################################
#### 0) loading and/or installing required libraries
###################################
if (!require("argparse")) {
  install.packages("argparse", ask =FALSE)
  library("argparse")
}
if (!require("gtools")) {
  install.packages("gtools", ask =FALSE)
  library("gtools")
}
if (!require("BiocManager")) {
  install.packages("BiocManager", ask =FALSE)
  library("BiocManager")
}
if (!require("limma")) {
  BiocManager::install("limma", ask =FALSE)
  library("limma")
}
if (!require("gtools")) {
  install.packages("gtools", ask =FALSE)
  library("gtools")
}
if (!require("tidyverse")) {
  install.packages("tidyverse", ask =FALSE)
  library("tidyverse")
}
########################################
#### data given by the user
#########################################
myargs <- commandArgs(trailingOnly = TRUE)

path_expression_matrix <- "/media/rmejia/mountme88/Projects/DSP/Data/Data_sent_by_DrAO_2020_12_11/RNA/NucleiLog2_QnormBatchSep_combat_2.txt"
path_expression_matrix <- myargs[1]

path_annotation_table <-"/media/rmejia/mountme88/Projects/DSP/Data/Data_sent_by_DrAO_2020_12_11/RNA/Final_annot_RNA_20201212_odd_deleted.tsv"
path_annotation_table <- myargs[2]

path_code <- myargs[3] 
path_code <- "/media/rmejia/mountme88/code/DSP-Oszwald"
path_code <- normalizePath( path_code )

Folder_to_save_results <- "/media/rmejia/mountme88/Projects/DSP/Results/DEG"
dir.create( Folder_to_save_results , recursive = TRUE)
Folder_to_save_results <- normalizePath(Folder_to_save_results)
Folder_to_save_results <- myargs[4]

column_of_labels_in_the_annotdf <- "label" # name of the column in your annotation data frame that contains the labels
column_of_labels_in_the_annotdf <- myargs[5]


Label_for_yor_results <- "RNA_"
Label_for_yor_results <- myargs[6]

############################
###### Body
#############################
# reading the your matrices
myexpmat <- read.table( file= path_expression_matrix , sep="\t", header = TRUE, row.names = 1)
annotdf <- read.table( file= path_annotation_table, sep="\t", header = TRUE, row.names = 1)

    # This chunk tries to match the intersecion of your expression matrix and your annotation (maybe you can relocate it in an independet script)
    # if you want to normalize
    colnames_expmat_nomarlized <- str_remove(colnames(myexpmat),"^X") # if a colname starts with a number R adds automatically an X
    rownames_annodf_normalized <- str_replace(rownames(annotdf),"a_","_") %>%  str_replace("b_","_") # Those are unmeagniful elements 

    positions_annot_in_expmat <- which( rownames_annodf_normalized %in% colnames_expmat_nomarlized)  # fitting annot_df to exp matrix
    annotdf_fitted_2_expmat <- annotdf[positions_annot_in_expmat,]

    positions_expmat_in_annot  <- which( colnames_expmat_nomarlized %in% rownames_annodf_normalized ) # fitting_exp to annot_df 
    expmat_fitted_2_annot <- myexpmat[,positions_expmat_in_annot]

# Desgin Matrix
designmat <- model.matrix( ~0+  as.factor( annotdf_fitted_2_expmat [,column_of_labels_in_the_annotdf]) )
    colnames(designmat) <- levels(as.factor( annotdf_fitted_2_expmat [,column_of_labels_in_the_annotdf] ))
   
# Fitting the lineal model    
myfit <- lmFit( expmat_fitted_2_annot , designmat  ) # fitting the linear model

mycontMat <- mymakeContrasts(designmat) # make your matrix of contrasts

myfit2 <- contrasts.fit( myfit, mycontMat)
myefit <- eBayes(myfit2) # moderate standard errors of the estimated log-fold changes



list_TopTable <- list()
list_TopTable[[1]] <- topTable( myefit , coef=1, adjust="BH", number = 200)
for(k in 2:dim(mycontMat)[2]){
  list_TopTable[[k]] <- topTable( myefit , coef=k, adjust="BH", number = 200)
}



topTable( myefit , coef=1, adjust="BH", number = 200)
topTable( myefit , coef=2, adjust="BH", number = 200)
topTable( myefit , coef=3, adjust="BH", number = 200)
topTable( myefit , coef=4, adjust="BH", number = 200)
topTable( myefit , coef=5, adjust="BH", number = 200)
topTable( myefit , coef=6, adjust="BH", number = 200)
topTable( myefit , coef=7, adjust="BH", number = 200)
topTable( myefit , coef=8, adjust="BH", number = 200)
topTable( myefit , coef=9, adjust="BH", number = 200)
topTable( myefit , coef=10, adjust="BH", number = 200)
topTable( myefit , coef=11, adjust="BH", number = 200)
topTable( myefit , coef=12, adjust="BH", number = 200)
topTable( myefit , coef=13, adjust="BH", number = 200)
topTable( myefit , coef=14, adjust="BH", number = 200)
topTable( myefit , coef=15, adjust="BH", number = 200)
topTable( myefit , coef=16, adjust="BH", number = 200)



myefit$design


# write.table

#results <- decideTests(myefit)
#vennDiagram(results)







  




